#!/usr/bin/env python

from ivolution.gui_wx import IvolutionWindow


import wx

app = wx.App(False)
frame = IvolutionWindow.IvolutionWindow(None, "Ivolution Window")
app.MainLoop()  # Runs application
