"""Subclass of IvolutionTemplate, which is generated by wxFormBuilder."""

import wx
import IvolutionTemplate.py

# Implementing IvolutionTemplate
class IvolutionV2IvolutionTemplate( IvolutionTemplate.py.IvolutionTemplate ):
	def __init__( self, parent ):
		IvolutionTemplate.py.IvolutionTemplate.__init__( self, parent )
	
